Update ECR kustomization.yml. Fix base path.
Base path is incorrect. Updated to correct value. 

Resolve error: 
kubectl apply -k .
error: couldn't make loader for ../../base: absolute path error in '/Users/<user>/k8s/image-substitution/aws-ebs-csi-driver/deploy/kubernetes/overlays/base' : evalsymlink failure on '/Users/<user>/k8s/image-substitution/aws-ebs-csi-driver/deploy/kubernetes/overlays/base' : lstat /Users/<user>/k8s/image-substitution/aws-ebs-csi-driver/deploy/kubernetes/overlays/base: no such file or directory